# Generated by Django 4.2.1 on 2023-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
